---
# https://github.com/gen2brain/keepalived_exporter/releases
# https://github.com/gen2brain/keepalived_exporter/releases/download/0.4.0/keepalived_exporter-0.4.0-amd64.tar.gz
- name: Set exporter facts
  set_fact:
    keepalived_exporter_sub_dir: "{{ exporter_config.exporter_dir | default('keepalived_exporter') }}"
    keepalived_exporter_user: "{{ exporter_config.exporter_user | default(prometheus_user) }}"
    keepalived_exporter_group: "{{ exporter_config.exporter_group | default(prometheus_group) }}"

- name: Prometheus keepalived exporter | check if this exporter version exists
  stat:
    path: "{{ prometheus_exporters_dir }}/keepalived_exporter-{{ prometheus_keepalived_exporter_version }}-amd64/"
  register: keepalived_exporter_version_exists
  become: yes

- name: Prometheus keepalived Exporter | Download distribution
  get_url:
    url: "https://github.com/gen2brain/keepalived_exporter/releases/download/{{ prometheus_keepalived_exporter_version }}/keepalived_exporter-{{ prometheus_keepalived_exporter_version }}-amd64.tar.gz"
    dest: "/tmp/keepalived_exporter-{{ prometheus_keepalived_exporter_version }}-amd64.tar.gz"
  become: yes
  become_user: "{{ keepalived_exporter_user }}"
  when: not keepalived_exporter_version_exists.stat.exists
  tags:
    - prometheus

- name: Prometheus keepalived Exporter | unpack distribution
  unarchive:
    src: "/tmp/keepalived_exporter-{{ prometheus_keepalived_exporter_version }}-amd64.tar.gz"
    dest: "{{ prometheus_exporters_dir }}"
    remote_src: yes
  become: yes
  become_user: "{{ keepalived_exporter_user }}"
  when: not keepalived_exporter_version_exists.stat.exists
  tags:
    - prometheus

- name: Prometheus keepalived Exporter | link keepalived exporter dir
  file:
    src: "{{ prometheus_exporters_dir }}/keepalived_exporter-{{ prometheus_keepalived_exporter_version }}-amd64/"
    dest: "{{ prometheus_exporters_dir }}/{{ keepalived_exporter_sub_dir }}"
    owner: "root"
    group: "{{ keepalived_exporter_group }}"
    state: link
  become: yes
  when: not keepalived_exporter_version_exists.stat.exists
  tags:
    - prometheus

- include_tasks: "tasks_startup.yml"
  vars:
    exporter_startup_config: "{{ exporter_config }}"
